import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Jhappi - A hug of hope</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <img src="/jhappi.jpg" height={"200"} />
        <h1 className={styles.title}>Coming soon</h1>
        <h2 className={styles.code} style={{ marginTop: "60px" }}>
          contact@jhappi.store
        </h2>
        <h2 className={styles.code}>9223369029</h2>
      </main>
    </div>
  );
}
